links:
  - name: "GitHub"
    url: https://github.com/TheArmagan
    icon: assets://github.png

languages:
  default: en
  supported:
    - en
    - tr

start-page: getting-started/start
icon: assets://github.png